/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.15 (master) - 15 Apr 2020 13:10
*/
#include <adBuffer.h>
#include "structures.h"

/*
  Differentiation of wall_bc in reverse (adjoint) mode:
   gradient     of useful results: *q[0:4-1] xy1[0:2-1] xy2[0:2-1]
   with respect to varying inputs: *q[0:4-1] xy1[0:2-1] xy2[0:2-1]
   RW status of diff variables: *q[0:4-1]:in-out xy1[0:2-1]:incr
                xy2[0:2-1]:incr
   Plus diff mem management of: q:in *q:in xy1:in xy2:in
*/
void wall_bc_bx(double (*q)[4], double (*qb)[4], double (*rhs)[4], Dim *dim, 
        double xy1[2], double xy1b[2], double xy2[2], double xy2b[2], int j, 
        int k) {
    int idx, widx, midx;
    int jstride = dim->jstride;
    int kstride = dim->kstride;
    int pad = dim->nghost;
    double Sx, Sy, imag2;
    double Sxb, Syb, imag2b;
    double temp;
    double tempb;
    double tmp;
    double tmpb;
    double tmp0;
    double tmpb0;
    double tempb0;
    double tempb1;
    double tmp1;
    double tmpb1;
    double tmp2;
    double tmpb2;
    Sx = -xy2[1] + xy1[1];
    Sy = xy2[0] - xy1[0];
    double u, v, irho, v_dot_wall, p;
    idx = j*dim->jstride + k*dim->kstride;
    midx = j*jstride + (2*dim->nghost-k-1)*kstride;
    // normalize wall vector
    imag2 = 1.0/(Sx*Sx+Sy*Sy);
    tmp = q[midx][0];
    q[idx][0] = tmp;
    tmp0 = q[midx][1] - 2.0*Sx*Sx*imag2*q[midx][1] - 2.0*Sx*Sy*imag2*q[midx][2
        ];
    pushReal8(q[idx][1]);
    q[idx][1] = tmp0;
    tmpb2 = qb[idx][3];
    qb[idx][3] = 0.0;
    qb[midx][3] = qb[midx][3] + tmpb2;
    tmpb1 = qb[idx][2];
    qb[idx][2] = 0.0;
    tempb1 = -(imag2*q[midx][1]*2.0*tmpb1);
    tempb0 = -(Sx*Sy*2.0*tmpb1);
    Syb = Sx*tempb1 - 2*Sy*imag2*q[midx][2]*2.0*tmpb1;
    tempb = -(Sy*Sy*2.0*tmpb1);
    qb[midx][2] = qb[midx][2] + tmpb1 + imag2*tempb;
    imag2b = q[midx][2]*tempb + q[midx][1]*tempb0;
    qb[midx][1] = qb[midx][1] + imag2*tempb0;
    Sxb = Sy*tempb1;
    popReal8(&(q[idx][1]));
    tmpb0 = qb[idx][1];
    qb[idx][1] = 0.0;
    tempb = -(Sx*Sx*2.0*tmpb0);
    qb[midx][1] = qb[midx][1] + tmpb0 + imag2*tempb;
    tempb0 = -(imag2*q[midx][2]*2.0*tmpb0);
    tempb1 = -(Sx*Sy*2.0*tmpb0);
    imag2b = imag2b + q[midx][2]*tempb1 + q[midx][1]*tempb;
    qb[midx][2] = qb[midx][2] + imag2*tempb1;
    tmpb = qb[idx][0];
    qb[idx][0] = 0.0;
    qb[midx][0] = qb[midx][0] + tmpb;
    temp = Sx*Sx + Sy*Sy;
    tempb = -(imag2b/(temp*temp));
    Sxb = Sxb + Sy*tempb0 - 2*Sx*imag2*q[midx][1]*2.0*tmpb0 + 2*Sx*tempb;
    Syb = Syb + Sx*tempb0 + 2*Sy*tempb;
    xy2b[0] = xy2b[0] + Syb;
    xy1b[0] = xy1b[0] - Syb;
    xy1b[1] = xy1b[1] + Sxb;
    xy2b[1] = xy2b[1] - Sxb;
}
