/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.12 (r6213) - 13 Oct 2016 10:30
*/
#include "adBuffer.h"
#include "../include/structures.h"

/*
  Differentiation of wall_bc in reverse (adjoint) mode:
   gradient     of useful results: *q[0:4-1] xy1[0:2-1] xy2[0:2-1]
   with respect to varying inputs: *q[0:4-1] xy1[0:2-1] xy2[0:2-1]
   RW status of diff variables: *q[0:4-1]:in-out xy1[0:2-1]:incr
                xy2[0:2-1]:incr
   Plus diff mem management of: q:in *q:in xy1:in xy2:in
*/
void wall_bc_bx(double (*q)[4], double (*qb)[4], double (*rhs)[4], Dim *dim, 
        double xy1[2], double xy1b[2], double xy2[2], double xy2b[2], int j, 
        int k) {
    int idx, widx, midx;
    int jstride = dim->jstride;
    int kstride = dim->kstride;
    int pad;
    double Sx, Sy, imag2;
    double Sxb, Syb, imag2b;
    double temp;
    double tmp;
    double tmp0;
    double tmp1;
    double tmp2;
    double tmpb;
    double tmpb0;
    double tempb;
    double tempb0;
    double tempb1;
    double tmpb1;
    double tempb2;
    double tempb3;
    double tempb4;
    double tempb5;
    double tmpb2;
    Sx = -xy2[1] + xy1[1];
    Sy = xy2[0] - xy1[0];
    double u, v, irho, v_dot_wall, p;
    idx = j*dim->jstride + k*dim->kstride;
    midx = j*jstride + (2*dim->nghost-k-1)*kstride;
    // normalize wall vector
    imag2 = 1.0/(Sx*Sx+Sy*Sy);
    tmp = q[midx][0];
    q[idx][0] = tmp;
    tmp0 = q[midx][1] - 2.0*Sx*Sx*imag2*q[midx][1] - 2.0*Sx*Sy*imag2*q[midx][2
        ];
    pushreal8(q[idx][1]);
    q[idx][1] = tmp0;
    tmpb = qb[idx][3];
    qb[idx][3] = 0.0;
    qb[midx][3] = qb[midx][3] + tmpb;
    tmpb0 = qb[idx][2];
    qb[idx][2] = 0.0;
    tempb = -(2.0*imag2*q[midx][1]*tmpb0);
    tempb0 = -(2.0*Sx*Sy*tmpb0);
    tempb1 = -(2.0*(Sy*Sy)*tmpb0);
    qb[midx][2] = qb[midx][2] + imag2*tempb1 + tmpb0;
    Syb = Sx*tempb - imag2*q[midx][2]*2.0*2*Sy*tmpb0;
    imag2b = q[midx][2]*tempb1 + q[midx][1]*tempb0;
    qb[midx][1] = qb[midx][1] + imag2*tempb0;
    popreal8(&q[idx][1]);
    tmpb1 = qb[idx][1];
    qb[idx][1] = 0.0;
    tempb4 = -(2.0*(Sx*Sx)*tmpb1);
    tempb2 = -(2.0*imag2*q[midx][2]*tmpb1);
    tempb5 = -(2.0*Sx*Sy*tmpb1);
    qb[midx][1] = qb[midx][1] + imag2*tempb4 + tmpb1;
    imag2b = imag2b + q[midx][2]*tempb5 + q[midx][1]*tempb4;
    qb[midx][2] = qb[midx][2] + imag2*tempb5;
    tmpb2 = qb[idx][0];
    qb[idx][0] = 0.0;
    qb[midx][0] = qb[midx][0] + tmpb2;
    temp = Sx*Sx + Sy*Sy;
    tempb3 = -(imag2b/(temp*temp));
    Sxb = Sy*tempb2 - imag2*q[midx][1]*2.0*2*Sx*tmpb1 + 2*Sx*tempb3 + Sy*tempb
    ;
    Syb = Syb + 2*Sy*tempb3 + Sx*tempb2;
    xy2b[0] = xy2b[0] + Syb;
    xy1b[0] = xy1b[0] - Syb;
    xy1b[1] = xy1b[1] + Sxb;
    xy2b[1] = xy2b[1] - Sxb;
}
